resources:
  repositories:
  - repository: BackendRepo
    type: github
    endpoint: github.com_TransmissionZ
    name: TransmissionZ/DevOps-Project-Backend


trigger:
- development



stages:
  - stage: BuildAndDeploy
    displayName: 'Build and Deploy'
    jobs:
      - job: BuildAndDeployJob
        displayName: 'Build and Deploy Job'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - checkout: self
          - checkout: BackendRepo
            
          - task: NodeTool@0
            inputs:
              versionSpec: '20.x'
            displayName: 'Install Node.js'

          - script: |
              npm install
              npm run build --if-present
              npm run test --if-present
            displayName: 'Build Node.js App'
            workingDirectory: '$(Build.SourcesDirectory)/DevOps-Project-FrontEnd'


          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: '$(System.DefaultWorkingDirectory)/app'
              artifactName: 'appPackage'
            displayName: 'Publish Artifact'

          - task: DownloadPipelineArtifact@2
            inputs:
              artifactName: 'appPackage'
              path: '$(System.DefaultWorkingDirectory)/deploy'
            displayName: 'Download Artifact'
            
          
          # - task: AzureWebApp@1
          #   displayName: 'Deploy to Azure Web App'
          #   inputs:
          #     azureSubscription: 'YourAzureSubscription'  # Replace with your Azure subscription name or ID
          #     appName: 'YourWebAppName'  # Replace with your Azure Web App name
          #     package: '$(System.DefaultWorkingDirectory)/deploy'
          #     startUpCommand: 'npm start'
          #     appType: webAppLinux
          # Halt Azure Web App
          

