resources:
  repositories:
  - repository: BackendRepo
    type: github
    endpoint: github.com_TransmissionZ
    name: TransmissionZ/DevOps-Project-Backend

trigger:
- main

pool:
  vmImage: ubuntu-latest

pr:
  branches:
    include:
      - '*'

stages:
  - stage: Frontend
    displayName: 'Build and Test Frontend'
    jobs:
      - job: Build
        displayName: 'Build Frontend'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - checkout: self

          - task: NodeTool@0
            inputs:
              versionSpec: '20.x'
            displayName: 'Install Node.js'
          
          - script: |
              npm install express
              npm install webpack webpack-cli
            displayName: 'Build Frontend'
      
      - job: Test
        displayName: 'Run Tests for Frontend'
        dependsOn: Build
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - checkout: self

          - task: NodeTool@0
            inputs:
              versionSpec: '20.x'
            displayName: 'Install Node.js'
            
          - script: |
              sudo apt install -y chromium-browser
              npm install --save-dev jest puppeteer
              npx jest frontend.test.js
            displayName: 'Run Tests for Frontend'

  - stage: Backend
    displayName: 'Build and Test Backend'
    jobs:
      - job: Build
        displayName: 'Build Backend'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - checkout: BackendRepo

          - task: NodeTool@0
            inputs:
              versionSpec: '20.x'
            displayName: 'Install Node.js'

          - script: |
              npm install express
            displayName: 'Install Dependencies'
      
      - job: Test
        displayName: 'Run Tests for Backend'
        dependsOn: Build
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - checkout: BackendRepo

          - task: NodeTool@0
            inputs:
              versionSpec: '20.x'
            displayName: 'Install Node.js'
            
          - script:
              npm install express
              npm install jest
              npm install supertest
              
              npx jest server.test.js --force-exit

            displayName: 'Run Tests for Backend'
          
          - task: CopyFiles@2
            displayName: 'Package Build Output'
            inputs:
              SourceFolder: '$(System.DefaultWorkingDirectory)'
              TargetFolder: '$(Build.ArtifactStagingDirectory)'

          # Step 3: Publish the artifact
          - task: PublishBuildArtifacts@1
            displayName: 'Publish Artifact'
            inputs:
              pathtoPublish: '$(Build.ArtifactStagingDirectory)'
              artifactName: 'CI_Backend_Artifact'