resources:
  repositories:
  - repository: BackendRepo
    type: github
    endpoint: github.com_TransmissionZ
    name: TransmissionZ/DevOps-Project-Backend


trigger:
- development

variables:
  app1Name: 'DevOps-Backend-WebApp'
  app2Name: 'DevOps-Frontend-Backend'



stages:
  - stage: BuildAndDeploy
    displayName: 'Build and Deploy'
    jobs:
      - job: BuildAndDeployJob
        displayName: 'Build and Deploy Job'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - checkout: self
          - checkout: BackendRepo
            
          - task: NodeTool@0
            inputs:
              versionSpec: '20.x'
            displayName: 'Install Node.js'

          - script: |
              npm install
              npm run build --if-present
              # npm run test --if-present
            displayName: 'Build Node.js App'
            workingDirectory: '$(Build.SourcesDirectory)/DevOps-Project-FrontEnd'

          - task: Docker@2
            displayName: 'Build Docker Image'
            inputs:
              command: 'buildAndPush'
              Dockerfile: '$(Build.SourcesDirectory)/DevOps-Project-FrontEnd/Dockerfile'
              tags: 'latest'
              containerRegistry: 'DockerHub'
              repository: 'transmissionz/devops_project'
          
          - task: AzureResourceManagerTemplateDeployment@3
            inputs:
              deploymentScope: 'Resource Group'
              azureResourceManagerConnection: 'sub1'
              subscriptionId: '6d7b5d55-66bd-44f2-8969-b29c81ad6214'
              action: 'Create Or Update Resource Group'
              resourceGroupName: 'DevOps_Project'
              location: 'East Asia'
              templateLocation: 'Linked artifact'
              csmFile: '$(Build.SourcesDirectory)/DevOps-Project-FrontEnd/azuredeploy.json'
              overrideParameters: '-app1Name $(app1Name) -app2Name $(app2Name)'
              deploymentMode: 'Incremental'
          
              
          - task: AzureWebApp@1
            inputs:
              azureSubscription: 'sub1'
              appType: 'webAppLinux'
              appName: 'DevOps-K190145-k190172'
              package: '$(Build.ArtifactStagingDirectory)/*.zip'
              startUpCommand: 'npm start'

          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: '$(System.DefaultWorkingDirectory)'
              artifactName: 'appPackage'
            displayName: 'Publish Artifact'

          - task: DownloadPipelineArtifact@2
            inputs:
              artifactName: 'appPackage'
              path: '$(System.DefaultWorkingDirectory)/deploy'
            displayName: 'Download Artifact'
            
          
          # Halt Azure Web App
          

